- name: Debian 11 SSH UFW
  ansible.builtin.apt:
    pkg:
      - ufw
    state: latest
    update_cache: true

- name: UFW - Allow SSH connections
  community.general.ufw:
    rule: allow
    name: OpenSSH
  when: not ansible_check_mode

- name: UFW - Enable and deny by default
  community.general.ufw:
    state: "{{ ssh_ufw_deb11_state }}"
    default: "{{ ssh_ufw_deb11_deny }}"
  when: not ansible_check_mode